# This is a basic workflow to help you get started with Actions

name: Update File

on:
 workflow_dispatch:
 schedule:
    - cron: "0 0 * * 0"

jobs:
  get_and_convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: wget
        uses: wei/wget@v1
        with:
          args: --no-check-certificate -O elenco-comuni-italiani.xls http://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.xls

      - name: Install csvkit
        run : |
          pip install csvkit
        
      - name: Convert to JSON
        run: |
          csvjson elenco-comuni-italiani.csv > elenco-comuni-italiani.json 

      - name: Convert to CSV
        run : |
            cat elenco-comuni-italiani.json | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' > elenco-comuni-italiani.csv
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Update


     